export type {
  AllergyIntolerance,
  BodyStructure,
  ClinicalDataLoadSummary,
  Condition,
  DeathRecord,
  DeathRecordDiagnosis,
  Encounter,
  FhirObservation,
  Immunization,
  LaboratoryOrderGroup,
  MedicationStatement,
  OpenEHRComposition,
  Patient,
  PatientSimilarityResult,
  Provenance,
  Procedure,
  QuestionnaireResponse,
  ServiceRequest
} from './patient.model';
