/**
 * AUTO-GENERATED by generate-eps-sections.mjs — do not edit by hand.
 * Structure (min/max/mustSupport) is derived from the HL7 EU EPS FHIR package;
 * field selection and SNOMED ECL bindings come from eps-sections.config.ts.
 */
import { EpsSectionMeta } from './eps-sections.model';

export const EPS_SECTIONS: EpsSectionMeta[] = [
  {
    "key": "problems",
    "kind": "resource",
    "title": "Problems",
    "loincCode": "11450-4",
    "resourceType": "Condition",
    "profile": "http://hl7.eu/fhir/eps/StructureDefinition/condition-obl-eu-eps",
    "profilePageUrl": "https://hl7.eu/fhir/eps/StructureDefinition-condition-obl-eu-eps.html",
    "icon": "coronavirus",
    "description": "Active problems and diagnoses on the patient’s problem list.",
    "fields": [
      {
        "key": "code",
        "path": "Condition.code",
        "label": "Problem",
        "control": "snomed",
        "min": 1,
        "max": "1",
        "mustSupport": true,
        "binding": {
          "ecl": "<< 404684003 |Clinical finding (finding)| OR << 243796009 |Situation with explicit context (situation)|",
          "title": "Problem / Diagnosis",
          "note": "Search a clinical finding or disorder"
        },
        "system": "http://snomed.info/sct",
        "doc": {
          "short": "Identification of the condition, problem or diagnosis",
          "definition": "The problem code specifies the problem. Depending on the setting, different code systems can be used. The ProblemCodelist provides an overview of the possible code systems.",
          "control": "1..1",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are preferred to http://hl7.org/fhir/uv/ips/ValueSet/problems-uv-ips.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-condition-obl-eu-eps-definitions.html#Condition.code"
        },
        "bindingMeta": {
          "strength": "preferred",
          "valueSet": "http://hl7.org/fhir/uv/ips/ValueSet/problems-uv-ips",
          "pageUrl": "https://hl7.org/fhir/uv/ips/ValueSet-problems-uv-ips.html",
          "isSct": true
        }
      },
      {
        "key": "clinicalStatus",
        "path": "Condition.clinicalStatus",
        "label": "Clinical status",
        "control": "dropdown",
        "min": 0,
        "max": "1",
        "mustSupport": true,
        "options": [
          {
            "code": "active",
            "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
            "display": "Active"
          },
          {
            "code": "recurrence",
            "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
            "display": "Recurrence"
          },
          {
            "code": "relapse",
            "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
            "display": "Relapse"
          },
          {
            "code": "inactive",
            "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
            "display": "Inactive"
          },
          {
            "code": "remission",
            "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
            "display": "Remission"
          },
          {
            "code": "resolved",
            "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
            "display": "Resolved"
          }
        ],
        "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
        "doc": {
          "short": "active | recurrence | relapse | inactive | remission | resolved",
          "definition": "The problem status describes the condition of the problem:\n\r\r\n1.\tActive problems are problems of which the patient experiences symptoms or for which evidence exists.\n\r\r\n2.\tIf condition is abated, then clinicalStatus must be either inactive, resolved, or remission. \n\r\r\n3.\tProblems with the status 'Inactive' refer to problems that don't affect the patient anymore or that of which there is no evidence of existence anymore.",
          "comment": "The data type is CodeableConcept because clinicalStatus has some clinical judgment involved, such that there might need to be more specificity than the required FHIR value set allows. For example, a SNOMED coding might allow for additional specificity.",
          "control": "0..1",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": true,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are required to http://hl7.org/fhir/ValueSet/condition-clinical.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-condition-obl-eu-eps-definitions.html#Condition.clinicalStatus"
        },
        "bindingMeta": {
          "strength": "required",
          "valueSet": "http://hl7.org/fhir/ValueSet/condition-clinical",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-condition-clinical.html",
          "isSct": false
        }
      },
      {
        "key": "severity",
        "path": "Condition.severity",
        "label": "Severity",
        "control": "dropdown",
        "min": 0,
        "max": "1",
        "mustSupport": true,
        "options": [
          {
            "code": "255604002",
            "system": "http://snomed.info/sct",
            "display": "Mild"
          },
          {
            "code": "6736007",
            "system": "http://snomed.info/sct",
            "display": "Moderate"
          },
          {
            "code": "24484000",
            "system": "http://snomed.info/sct",
            "display": "Severe"
          }
        ],
        "system": "http://snomed.info/sct",
        "doc": {
          "short": "Subjective severity of condition",
          "definition": "A subjective assessment of the severity of the condition as evaluated by the clinician.",
          "comment": "Coding of the severity with a terminology is preferred, where possible.",
          "control": "0..1",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": false,
          "isSummary": false,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are preferred to http://hl7.org/fhir/ValueSet/condition-severity.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-condition-obl-eu-eps-definitions.html#Condition.severity"
        },
        "bindingMeta": {
          "strength": "preferred",
          "valueSet": "http://hl7.org/fhir/ValueSet/condition-severity",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-condition-severity.html",
          "isSct": false
        }
      },
      {
        "key": "onset",
        "path": "Condition.onset[x]",
        "label": "Onset date",
        "control": "date",
        "min": 0,
        "max": "1",
        "mustSupport": true,
        "doc": {
          "short": "Estimated or actual date,  date-time, or age",
          "definition": "Estimated or actual date or date-time  the condition began, in the opinion of the clinician.",
          "comment": "Age is generally used when the patient reports an age at which the Condition began to occur.",
          "control": "0..1",
          "types": [
            "dateTime",
            "Age",
            "Period",
            "Range",
            "string"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-condition-obl-eu-eps-definitions.html#Condition.onset[x]"
        }
      }
    ]
  },
  {
    "key": "allergies",
    "kind": "resource",
    "title": "Allergies & Intolerances",
    "loincCode": "48765-2",
    "resourceType": "AllergyIntolerance",
    "profile": "http://hl7.eu/fhir/eps/StructureDefinition/allergyintolerance-obl-eu-eps",
    "profilePageUrl": "https://hl7.eu/fhir/eps/StructureDefinition-allergyintolerance-obl-eu-eps.html",
    "icon": "warning_amber",
    "description": "Allergies and intolerances, including the causative agent and reaction.",
    "fields": [
      {
        "key": "code",
        "path": "AllergyIntolerance.code",
        "label": "Causative agent",
        "control": "snomed",
        "min": 1,
        "max": "1",
        "mustSupport": true,
        "binding": {
          "ecl": "< 105590001 |Substance (substance)| OR < 763158003 |Medicinal product (product)|",
          "title": "Allergy / Intolerance agent",
          "note": "Search a substance or medicinal product"
        },
        "system": "http://snomed.info/sct",
        "doc": {
          "short": "Code that identifies the allergy or intolerance",
          "definition": "Code for an allergy or intolerance statement (either a positive or a negated/excluded statement).  This may be a code for a substance or pharmaceutical product that is considered to be responsible for the adverse reaction risk (e.g., \"Latex\"), an allergy or intolerance condition (e.g., \"Latex allergy\"), or a negated/excluded code for a specific substance or class (e.g., \"No latex allergy\") or a general or categorical negated statement (e.g.,  \"No known allergy\", \"No known drug allergies\").  Note: the substance for a specific reaction may be different from the substance identified as the cause of the risk, but it must be consistent with it. For instance, it may be a more specific substance (e.g. a brand medication) or a composite product that includes the identified substance. It must be clinically safe to only process the 'code' and ignore the 'reaction.substance'.  If a receiving system is unable to confirm that AllergyIntolerance.reaction.substance falls within the semantic scope of AllergyIntolerance.code, then the receiving system should ignore AllergyIntolerance.reaction.substance.",
          "comment": "It is strongly recommended that this element be populated using a terminology, where possible. For example, some terminologies used include RxNorm, SNOMED CT, DM+D, NDFRT, ICD-9, IDC-10, UNII, and ATC. Plain text should only be used if there is no appropriate terminology available. Additional details can be specified in the text.\r\rWhen a substance or product code is specified for the 'code' element, the \"default\" semantic context is that this is a positive statement of an allergy or intolerance (depending on the value of the 'type' element, if present) condition to the specified substance/product.  In the corresponding SNOMED CT allergy model, the specified substance/product is the target (destination) of the \"Causative agent\" relationship.\r\rThe 'substanceExposureRisk' extension is available as a structured and more flexible alternative to the 'code' element for making positive or negative allergy or intolerance statements.  This extension provides the capability to make \"no known allergy\" (or \"no risk of adverse reaction\") statements regarding any coded substance/product (including cases when a pre-coordinated \"no allergy to x\" concept for that substance/product does not exist).  If the 'substanceExposureRisk' extension is present, the AllergyIntolerance.code element SHALL be omitted.",
          "control": "1..1",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are preferred to http://hl7.org/fhir/uv/ips/ValueSet/allergies-intolerances-uv-ips.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-allergyintolerance-obl-eu-eps-definitions.html#AllergyIntolerance.code"
        },
        "bindingMeta": {
          "strength": "preferred",
          "valueSet": "http://hl7.org/fhir/uv/ips/ValueSet/allergies-intolerances-uv-ips",
          "pageUrl": "https://hl7.org/fhir/uv/ips/ValueSet-allergies-intolerances-uv-ips.html",
          "isSct": true
        }
      },
      {
        "key": "type",
        "path": "AllergyIntolerance.type",
        "label": "Type",
        "control": "dropdown",
        "min": 0,
        "max": "1",
        "mustSupport": true,
        "options": [
          {
            "code": "allergy",
            "system": "http://hl7.org/fhir/allergy-intolerance-type",
            "display": "Allergy"
          },
          {
            "code": "intolerance",
            "system": "http://hl7.org/fhir/allergy-intolerance-type",
            "display": "Intolerance"
          }
        ],
        "system": "http://hl7.org/fhir/allergy-intolerance-type",
        "doc": {
          "short": "Type of propensity",
          "definition": "Identification of the underlying physiological mechanism for the reaction risk.",
          "comment": "Allergic (typically immune-mediated) reactions have been traditionally regarded as an indicator for potential escalation to significant future risk. Contemporary knowledge suggests that some reactions previously thought to be immune-mediated are, in fact, non-immune, but in some cases can still pose a life threatening risk. It is acknowledged that many clinicians might not be in a position to distinguish the mechanism of a particular reaction. Often the term \"allergy\" is used rather generically and may overlap with the use of \"intolerance\" - in practice the boundaries between these two concepts might not be well-defined or understood. This data element is included nevertheless, because many legacy systems have captured this attribute. Immunologic testing may provide supporting evidence for the basis of the reaction and the causative substance, but no tests are 100% sensitive or specific for sensitivity to a particular substance. If, as is commonly the case, it is unclear whether the reaction is due to an allergy or an intolerance, then the type element should be omitted from the resource.",
          "control": "0..1",
          "types": [
            "code"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are required to http://hl7.org/fhir/ValueSet/allergy-intolerance-type.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-allergyintolerance-obl-eu-eps-definitions.html#AllergyIntolerance.type"
        },
        "bindingMeta": {
          "strength": "required",
          "valueSet": "http://hl7.org/fhir/ValueSet/allergy-intolerance-type",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-allergy-intolerance-type.html",
          "isSct": false
        }
      },
      {
        "key": "clinicalStatus",
        "path": "AllergyIntolerance.clinicalStatus",
        "label": "Clinical status",
        "control": "dropdown",
        "min": 0,
        "max": "1",
        "mustSupport": true,
        "options": [
          {
            "code": "active",
            "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical",
            "display": "Active"
          },
          {
            "code": "inactive",
            "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical",
            "display": "Inactive"
          },
          {
            "code": "resolved",
            "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical",
            "display": "Resolved"
          }
        ],
        "system": "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical",
        "doc": {
          "short": "Current allergy or Intolerance status",
          "definition": "The clinical status of the allergy or intolerance.",
          "comment": "Refer to [discussion](http://hl7.org/fhir/R4/extensibility.html#Special-Case) if clincalStatus is missing data.\nThe data type is CodeableConcept because clinicalStatus has some clinical judgment involved, such that there might need to be more specificity than the required FHIR value set allows. For example, a SNOMED coding might allow for additional specificity.",
          "control": "0..1",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": true,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are required to http://hl7.org/fhir/ValueSet/allergyintolerance-clinical.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-allergyintolerance-obl-eu-eps-definitions.html#AllergyIntolerance.clinicalStatus"
        },
        "bindingMeta": {
          "strength": "required",
          "valueSet": "http://hl7.org/fhir/ValueSet/allergyintolerance-clinical",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-allergyintolerance-clinical.html",
          "isSct": false
        }
      },
      {
        "key": "manifestation",
        "path": "AllergyIntolerance.reaction.manifestation",
        "label": "Reaction manifestation",
        "control": "snomed",
        "min": 1,
        "max": "*",
        "mustSupport": true,
        "binding": {
          "ecl": "<< 404684003 |Clinical finding (finding)|",
          "title": "Reaction manifestation",
          "note": "Search the clinical manifestation of the reaction"
        },
        "system": "http://snomed.info/sct",
        "doc": {
          "short": "Clinical symptoms/signs associated with the Event",
          "definition": "Clinical symptoms and/or signs that are observed or associated with the adverse reaction event.",
          "comment": "Manifestation can be expressed as a single word, phrase or brief description. For example: nausea, rash or no reaction. It is preferable that manifestation should be coded with a terminology, where possible. The values entered here may be used to display on an application screen as part of a list of adverse reactions, as recommended in the UK NHS CUI guidelines.  Terminologies commonly used include, but are not limited to, SNOMED CT or ICD10.",
          "control": "1..*",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": false,
          "isSummary": false,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are preferred to http://hl7.org/fhir/uv/ips/ValueSet/allergy-reaction-uv-ips.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-allergyintolerance-obl-eu-eps-definitions.html#AllergyIntolerance.reaction.manifestation"
        },
        "bindingMeta": {
          "strength": "preferred",
          "valueSet": "http://hl7.org/fhir/uv/ips/ValueSet/allergy-reaction-uv-ips",
          "pageUrl": "https://hl7.org/fhir/uv/ips/ValueSet-allergy-reaction-uv-ips.html",
          "isSct": true
        }
      },
      {
        "key": "reactionSeverity",
        "path": "AllergyIntolerance.reaction.severity",
        "label": "Reaction severity",
        "control": "dropdown",
        "min": 0,
        "max": "1",
        "mustSupport": true,
        "options": [
          {
            "code": "mild",
            "system": "http://hl7.org/fhir/reaction-event-severity",
            "display": "Mild"
          },
          {
            "code": "moderate",
            "system": "http://hl7.org/fhir/reaction-event-severity",
            "display": "Moderate"
          },
          {
            "code": "severe",
            "system": "http://hl7.org/fhir/reaction-event-severity",
            "display": "Severe"
          }
        ],
        "system": "http://hl7.org/fhir/reaction-event-severity",
        "doc": {
          "short": "Reaction severity",
          "definition": "Clinical assessment of the severity of the reaction event as a whole, potentially considering multiple different manifestations.",
          "comment": "It is acknowledged that this assessment is very subjective. There may be some specific practice domains where objective scales have been applied. Objective scales can be included in this model as extensions.",
          "control": "0..1",
          "types": [
            "code"
          ],
          "isModifier": false,
          "isSummary": false,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are required to http://hl7.org/fhir/ValueSet/reaction-event-severity.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-allergyintolerance-obl-eu-eps-definitions.html#AllergyIntolerance.reaction.severity"
        },
        "bindingMeta": {
          "strength": "required",
          "valueSet": "http://hl7.org/fhir/ValueSet/reaction-event-severity",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-reaction-event-severity.html",
          "isSct": false
        }
      },
      {
        "key": "onset",
        "path": "AllergyIntolerance.onset[x]",
        "label": "Onset date",
        "control": "date",
        "min": 0,
        "max": "1",
        "mustSupport": true,
        "doc": {
          "short": "Date of onset of the allergy or intolerance",
          "definition": "Estimated or actual date,  date-time, or age when allergy or intolerance was identified.",
          "control": "0..1",
          "types": [
            "dateTime",
            "Age",
            "Period",
            "Range",
            "string"
          ],
          "isModifier": false,
          "isSummary": false,
          "invariants": [
            "ele-1"
          ],
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-allergyintolerance-obl-eu-eps-definitions.html#AllergyIntolerance.onset[x]"
        }
      }
    ]
  },
  {
    "key": "medications",
    "kind": "resource",
    "title": "Medication Summary",
    "loincCode": "10160-0",
    "resourceType": "MedicationStatement",
    "profile": "http://hl7.eu/fhir/eps/StructureDefinition/MedicationStatement-eu-eps",
    "profilePageUrl": "https://hl7.eu/fhir/eps/StructureDefinition-MedicationStatement-eu-eps.html",
    "icon": "medication",
    "description": "Current and relevant past medication, as a coded product with dosage.",
    "fields": [
      {
        "key": "medication",
        "path": "MedicationStatement.medication[x]",
        "label": "Medicinal product",
        "control": "snomed",
        "min": 1,
        "max": "1",
        "mustSupport": true,
        "binding": {
          "ecl": "<< 763158003 |Medicinal product (product)|",
          "title": "Medicinal product",
          "note": "Search a medicinal product"
        },
        "system": "http://snomed.info/sct",
        "doc": {
          "short": "What medication was taken",
          "definition": "Identifies the medication being administered. This is either a link to a resource representing the details of the medication or a simple attribute carrying a code that identifies the medication from a known list of medications.",
          "comment": "If only a code is specified, then it needs to be a code for a specific product. If more information is required, then the use of the medication resource is recommended.  For example, if you require form or lot number, then you must reference the Medication resource.",
          "control": "1..1",
          "types": [
            "CodeableConcept",
            "Reference"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are example to http://hl7.org/fhir/uv/ips/ValueSet/medication-uv-ips.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-MedicationStatement-eu-eps-definitions.html#MedicationStatement.medication[x]"
        },
        "bindingMeta": {
          "strength": "example",
          "valueSet": "http://hl7.org/fhir/uv/ips/ValueSet/medication-uv-ips",
          "pageUrl": "https://hl7.org/fhir/uv/ips/ValueSet-medication-uv-ips.html",
          "isSct": true
        }
      },
      {
        "key": "status",
        "path": "MedicationStatement.status",
        "label": "Status",
        "control": "dropdown",
        "min": 1,
        "max": "1",
        "mustSupport": false,
        "options": [
          {
            "code": "active",
            "system": "http://hl7.org/fhir/CodeSystem/medication-statement-status",
            "display": "Active"
          },
          {
            "code": "completed",
            "system": "http://hl7.org/fhir/CodeSystem/medication-statement-status",
            "display": "Completed"
          },
          {
            "code": "stopped",
            "system": "http://hl7.org/fhir/CodeSystem/medication-statement-status",
            "display": "Stopped"
          },
          {
            "code": "on-hold",
            "system": "http://hl7.org/fhir/CodeSystem/medication-statement-status",
            "display": "On hold"
          },
          {
            "code": "intended",
            "system": "http://hl7.org/fhir/CodeSystem/medication-statement-status",
            "display": "Intended"
          }
        ],
        "system": "http://hl7.org/fhir/CodeSystem/medication-statement-status",
        "doc": {
          "short": "State of the medication",
          "definition": "A code representing the patient or other source's judgment about the state of the medication used that this statement is about.  Generally, this will be active or completed.",
          "comment": "MedicationStatement is a statement at a point in time.  The status is only representative at the point when it was asserted.  The value set for MedicationStatement.status contains codes that assert the status of the use of the medication by the patient (for example, stopped or on hold) as well as codes that assert the status of the medication statement itself (for example, entered in error).\r\rThis element is labeled as a modifier because the status contains codes that mark the resource as not currently valid.",
          "control": "1..1",
          "types": [
            "code"
          ],
          "isModifier": true,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are required to http://hl7.org/fhir/ValueSet/medication-statement-status.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-MedicationStatement-eu-eps-definitions.html#MedicationStatement.status"
        },
        "bindingMeta": {
          "strength": "required",
          "valueSet": "http://hl7.org/fhir/ValueSet/medication-statement-status",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-medication-statement-status.html",
          "isSct": false
        }
      },
      {
        "key": "effective",
        "path": "MedicationStatement.effective[x]",
        "label": "Effective date",
        "control": "date",
        "min": 0,
        "max": "1",
        "mustSupport": true,
        "doc": {
          "short": "The date/time or interval when the medication is/was/will be taken",
          "definition": "The interval of time during which it is being asserted that the patient is/was/will be taking the medication (or was not taking, when the MedicationStatement.taken element is No).",
          "comment": "This attribute reflects the period over which the patient consumed the medication and is expected to be populated on the majority of Medication Statements. If the medication is still being taken at the time the statement is recorded, the \"end\" date will be omitted.  The date/time attribute supports a variety of dates - year, year/month and exact date.  If something more than this is required, this should be conveyed as text.",
          "control": "0..1",
          "types": [
            "dateTime",
            "Period"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-MedicationStatement-eu-eps-definitions.html#MedicationStatement.effective[x]"
        }
      },
      {
        "key": "dosageText",
        "path": "MedicationStatement.dosage.text",
        "label": "Dosage instructions",
        "control": "text",
        "min": 0,
        "max": "1",
        "mustSupport": true,
        "hint": "Free-text dosage, e.g. “1 tablet every 8 hours”",
        "doc": {
          "short": "Free text dosage instructions e.g. SIG",
          "definition": "Free text dosage instructions e.g. SIG.",
          "control": "0..1",
          "types": [
            "string"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-MedicationStatement-eu-eps-definitions.html#MedicationStatement.dosage.text"
        }
      }
    ]
  },
  {
    "key": "immunizations",
    "kind": "resource",
    "title": "Immunizations",
    "loincCode": "11369-6",
    "resourceType": "Immunization",
    "profile": "http://hl7.eu/fhir/eps/StructureDefinition/immunization-obl-eu-eps",
    "profilePageUrl": "https://hl7.eu/fhir/eps/StructureDefinition-immunization-obl-eu-eps.html",
    "icon": "vaccines",
    "description": "Immunization history: vaccines administered to the patient.",
    "fields": [
      {
        "key": "vaccineCode",
        "path": "Immunization.vaccineCode",
        "label": "Vaccine",
        "control": "snomed",
        "min": 1,
        "max": "1",
        "mustSupport": true,
        "binding": {
          "ecl": "<< 787859002 |Vaccine product (product)|",
          "title": "Vaccine",
          "note": "Search a vaccine product"
        },
        "system": "http://snomed.info/sct",
        "doc": {
          "short": "Vaccine product administered",
          "definition": "Vaccine that was administered or was to be administered.",
          "control": "1..1",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are preferred to http://hl7.org/fhir/uv/ips/ValueSet/vaccines-uv-ips.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-immunization-obl-eu-eps-definitions.html#Immunization.vaccineCode"
        },
        "bindingMeta": {
          "strength": "preferred",
          "valueSet": "http://hl7.org/fhir/uv/ips/ValueSet/vaccines-uv-ips",
          "pageUrl": "https://hl7.org/fhir/uv/ips/ValueSet-vaccines-uv-ips.html",
          "isSct": true
        }
      },
      {
        "key": "status",
        "path": "Immunization.status",
        "label": "Status",
        "control": "dropdown",
        "min": 1,
        "max": "1",
        "mustSupport": true,
        "options": [
          {
            "code": "completed",
            "system": "http://hl7.org/fhir/event-status",
            "display": "Completed"
          },
          {
            "code": "entered-in-error",
            "system": "http://hl7.org/fhir/event-status",
            "display": "Entered in error"
          },
          {
            "code": "not-done",
            "system": "http://hl7.org/fhir/event-status",
            "display": "Not done"
          }
        ],
        "system": "http://hl7.org/fhir/event-status",
        "doc": {
          "short": "Immunization status.",
          "definition": "Indicates the current status of the immunization event.",
          "comment": "Will generally be set to show that the immunization has been completed or not done.  This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid.",
          "control": "1..1",
          "types": [
            "code"
          ],
          "isModifier": true,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are required to http://hl7.org/fhir/ValueSet/immunization-status.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-immunization-obl-eu-eps-definitions.html#Immunization.status"
        },
        "bindingMeta": {
          "strength": "required",
          "valueSet": "http://hl7.org/fhir/ValueSet/immunization-status",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-immunization-status.html",
          "isSct": false
        }
      },
      {
        "key": "occurrence",
        "path": "Immunization.occurrence[x]",
        "label": "Date administered",
        "control": "date",
        "min": 0,
        "max": "1",
        "mustSupport": true,
        "doc": {
          "short": "Date of vaccination",
          "definition": "Date vaccine administered or was to be administered.",
          "comment": "When immunizations are given a specific date and time should always be known.   When immunizations are patient reported, a specific date might not be known.  Although partial dates are allowed, an adult patient might not be able to recall the year a childhood immunization was given. An exact date is always preferable, but the use of the String data type is acceptable when an exact date is not known. A small number of vaccines (e.g. live oral typhoid vaccine) are given as a series of patient self-administered dose over a span of time. In cases like this, often, only the first dose (typically a provider supervised dose) is recorded with the occurrence indicating the date/time of the first dose.",
          "control": "0..1",
          "types": [
            "dateTime",
            "string"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-immunization-obl-eu-eps-definitions.html#Immunization.occurrence[x]"
        }
      },
      {
        "key": "site",
        "path": "Immunization.site",
        "label": "Body site",
        "control": "snomed",
        "min": 0,
        "max": "1",
        "mustSupport": false,
        "binding": {
          "ecl": "<< 123037004 |Body structure (body structure)|",
          "title": "Administration site",
          "note": "Search a body structure"
        },
        "system": "http://snomed.info/sct",
        "doc": {
          "short": "Body site vaccine  was administered",
          "definition": "Body site where vaccine was administered.",
          "control": "0..1",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": false,
          "isSummary": false,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are example to http://hl7.org/fhir/ValueSet/immunization-site.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-immunization-obl-eu-eps-definitions.html#Immunization.site"
        },
        "bindingMeta": {
          "strength": "example",
          "valueSet": "http://hl7.org/fhir/ValueSet/immunization-site",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-immunization-site.html",
          "isSct": true
        }
      }
    ]
  },
  {
    "key": "procedures",
    "kind": "resource",
    "title": "Procedures",
    "loincCode": "47519-4",
    "resourceType": "Procedure",
    "profile": "http://hl7.eu/fhir/eps/StructureDefinition/procedure-eu-eps",
    "profilePageUrl": "https://hl7.eu/fhir/eps/StructureDefinition-procedure-eu-eps.html",
    "icon": "medical_information",
    "description": "History of procedures performed on the patient.",
    "fields": [
      {
        "key": "code",
        "path": "Procedure.code",
        "label": "Procedure",
        "control": "snomed",
        "min": 1,
        "max": "1",
        "mustSupport": true,
        "binding": {
          "ecl": "<< 71388002 |Procedure (procedure)|",
          "title": "Procedure",
          "note": "Search a procedure"
        },
        "system": "http://snomed.info/sct",
        "doc": {
          "short": "Identification of the procedure",
          "definition": "Identification of the procedure or recording of \"absence of relevant procedures\" or of \"procedures unknown\".",
          "control": "1..1",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are preferred to http://hl7.org/fhir/uv/ips/ValueSet/procedures-uv-ips.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-procedure-eu-eps-definitions.html#Procedure.code"
        },
        "bindingMeta": {
          "strength": "preferred",
          "valueSet": "http://hl7.org/fhir/uv/ips/ValueSet/procedures-uv-ips",
          "pageUrl": "https://hl7.org/fhir/uv/ips/ValueSet-procedures-uv-ips.html",
          "isSct": true
        }
      },
      {
        "key": "status",
        "path": "Procedure.status",
        "label": "Status",
        "control": "dropdown",
        "min": 1,
        "max": "1",
        "mustSupport": false,
        "options": [
          {
            "code": "preparation",
            "system": "http://hl7.org/fhir/event-status",
            "display": "Preparation"
          },
          {
            "code": "in-progress",
            "system": "http://hl7.org/fhir/event-status",
            "display": "In progress"
          },
          {
            "code": "not-done",
            "system": "http://hl7.org/fhir/event-status",
            "display": "Not done"
          },
          {
            "code": "on-hold",
            "system": "http://hl7.org/fhir/event-status",
            "display": "On hold"
          },
          {
            "code": "stopped",
            "system": "http://hl7.org/fhir/event-status",
            "display": "Stopped"
          },
          {
            "code": "completed",
            "system": "http://hl7.org/fhir/event-status",
            "display": "Completed"
          },
          {
            "code": "entered-in-error",
            "system": "http://hl7.org/fhir/event-status",
            "display": "Entered in error"
          },
          {
            "code": "unknown",
            "system": "http://hl7.org/fhir/event-status",
            "display": "Unknown"
          }
        ],
        "system": "http://hl7.org/fhir/event-status",
        "doc": {
          "short": "The status of the procedure",
          "definition": "A code specifying the state of the procedure. Generally, this will be the in-progress or completed state.",
          "comment": "The \"unknown\" code is not to be used to convey other statuses.  The \"unknown\" code should be used when one of the statuses applies, but the authoring system doesn't know the current state of the procedure.\n\nThis element is labeled as a modifier because the status contains codes that mark the resource as not currently valid.",
          "control": "1..1",
          "types": [
            "code"
          ],
          "isModifier": true,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are required to http://hl7.org/fhir/ValueSet/event-status.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-procedure-eu-eps-definitions.html#Procedure.status"
        },
        "bindingMeta": {
          "strength": "required",
          "valueSet": "http://hl7.org/fhir/ValueSet/event-status",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-event-status.html",
          "isSct": false
        }
      },
      {
        "key": "performed",
        "path": "Procedure.performed[x]",
        "label": "Performed date",
        "control": "date",
        "min": 0,
        "max": "1",
        "mustSupport": true,
        "doc": {
          "short": "When the procedure was performed",
          "definition": "Estimated or actual date, date-time, period, or age when the procedure was performed.  Allows a period to support complex procedures that span more than one date, and also allows for the length of the procedure to be captured.",
          "comment": "Age is generally used when the patient reports an age at which the procedure was performed. Range is generally used when the patient reports an age range when the procedure was performed, such as sometime between 20-25 years old.  dateTime supports a range of precision due to some procedures being reported as past procedures that might not have millisecond precision while other procedures performed and documented during the encounter might have more precise UTC timestamps with timezone.",
          "control": "0..1",
          "types": [
            "dateTime",
            "Period",
            "string",
            "Age",
            "Range"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-procedure-eu-eps-definitions.html#Procedure.performed[x]"
        }
      },
      {
        "key": "bodySite",
        "path": "Procedure.bodySite",
        "label": "Body site",
        "control": "snomed",
        "min": 0,
        "max": "*",
        "mustSupport": false,
        "binding": {
          "ecl": "<< 123037004 |Body structure (body structure)|",
          "title": "Body site",
          "note": "Search a body structure"
        },
        "system": "http://snomed.info/sct",
        "doc": {
          "short": "Target body sites",
          "definition": "Anatomical location which is the focus of the problem.",
          "comment": "If the use case requires attributes from the BodySite resource (e.g. to identify and track separately) then use the standard extension [procedure-targetbodystructure](http://hl7.org/fhir/R4/extension-procedure-targetbodystructure.html).",
          "control": "0..*",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1",
            "eu-bodysite-1"
          ],
          "bindingText": "The codes are preferred to http://hl7.org/fhir/ValueSet/body-site.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-procedure-eu-eps-definitions.html#Procedure.bodySite"
        },
        "bindingMeta": {
          "strength": "preferred",
          "valueSet": "http://hl7.org/fhir/ValueSet/body-site",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-body-site.html",
          "isSct": true
        }
      }
    ]
  },
  {
    "key": "alerts",
    "kind": "resource",
    "title": "Alerts",
    "loincCode": "104605-1",
    "resourceType": "Flag",
    "profile": "http://hl7.eu/fhir/eps/StructureDefinition/flag-alert-obl-eu-eps",
    "profilePageUrl": "https://hl7.eu/fhir/eps/StructureDefinition-flag-alert-obl-eu-eps.html",
    "icon": "flag",
    "description": "Clinical alerts and flags to be aware of for this patient.",
    "fields": [
      {
        "key": "code",
        "path": "Flag.code",
        "label": "Alert",
        "control": "snomed",
        "min": 1,
        "max": "1",
        "mustSupport": true,
        "binding": {
          "ecl": "<< 404684003 |Clinical finding (finding)| OR << 243796009 |Situation with explicit context (situation)|",
          "title": "Alert",
          "note": "Search a clinical finding or situation"
        },
        "system": "http://snomed.info/sct",
        "doc": {
          "short": "Coded or textual message to display to user.",
          "definition": "The coded value or textual component of the flag to display to the user.",
          "comment": "If non-coded, use CodeableConcept.text.  This element should always be included in the narrative.",
          "control": "1..1",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are example to http://hl7.org/fhir/ValueSet/flag-code.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-flag-alert-obl-eu-eps-definitions.html#Flag.code"
        },
        "bindingMeta": {
          "strength": "example",
          "valueSet": "http://hl7.org/fhir/ValueSet/flag-code",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-flag-code.html",
          "isSct": true
        }
      },
      {
        "key": "category",
        "path": "Flag.category",
        "label": "Category",
        "control": "dropdown",
        "min": 0,
        "max": "*",
        "mustSupport": true,
        "options": [
          {
            "code": "clinical",
            "system": "http://terminology.hl7.org/CodeSystem/flag-category",
            "display": "Clinical"
          },
          {
            "code": "drug",
            "system": "http://terminology.hl7.org/CodeSystem/flag-category",
            "display": "Drug"
          },
          {
            "code": "lab",
            "system": "http://terminology.hl7.org/CodeSystem/flag-category",
            "display": "Laboratory"
          },
          {
            "code": "diet",
            "system": "http://terminology.hl7.org/CodeSystem/flag-category",
            "display": "Diet"
          },
          {
            "code": "safety",
            "system": "http://terminology.hl7.org/CodeSystem/flag-category",
            "display": "Safety"
          },
          {
            "code": "behavioral",
            "system": "http://terminology.hl7.org/CodeSystem/flag-category",
            "display": "Behavioral"
          }
        ],
        "system": "http://terminology.hl7.org/CodeSystem/flag-category",
        "doc": {
          "short": "Clinical, administrative, etc.",
          "definition": "Allows a flag to be divided into different categories like clinical, administrative etc. Intended to be used as a means of filtering which flags are displayed to particular user or in a given context.",
          "comment": "The value set will often need to be adjusted based on local business rules and usage context.",
          "control": "0..*",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are example to http://hl7.org/fhir/ValueSet/flag-category.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-flag-alert-obl-eu-eps-definitions.html#Flag.category"
        },
        "bindingMeta": {
          "strength": "example",
          "valueSet": "http://hl7.org/fhir/ValueSet/flag-category",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-flag-category.html",
          "isSct": false
        }
      },
      {
        "key": "status",
        "path": "Flag.status",
        "label": "Status",
        "control": "dropdown",
        "min": 1,
        "max": "1",
        "mustSupport": false,
        "options": [
          {
            "code": "active",
            "system": "http://hl7.org/fhir/flag-status",
            "display": "Active"
          },
          {
            "code": "inactive",
            "system": "http://hl7.org/fhir/flag-status",
            "display": "Inactive"
          },
          {
            "code": "entered-in-error",
            "system": "http://hl7.org/fhir/flag-status",
            "display": "Entered in error"
          }
        ],
        "system": "http://hl7.org/fhir/flag-status",
        "doc": {
          "short": "Alert status",
          "definition": "Supports basic workflow.",
          "comment": "This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid.",
          "control": "1..1",
          "types": [
            "code"
          ],
          "isModifier": true,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are required to http://hl7.org/fhir/ValueSet/flag-status.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-flag-alert-obl-eu-eps-definitions.html#Flag.status"
        },
        "bindingMeta": {
          "strength": "required",
          "valueSet": "http://hl7.org/fhir/ValueSet/flag-status",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-flag-status.html",
          "isSct": false
        }
      }
    ]
  },
  {
    "key": "medicalDevices",
    "kind": "resource",
    "title": "Medical Devices",
    "loincCode": "46264-8",
    "resourceType": "DeviceUseStatement",
    "profile": "http://hl7.eu/fhir/eps/StructureDefinition/deviceUseStatement-eu-eps",
    "profilePageUrl": "https://hl7.eu/fhir/eps/StructureDefinition-deviceUseStatement-eu-eps.html",
    "icon": "monitor_heart",
    "description": "Medical devices and implants used by the patient.",
    "fields": [
      {
        "key": "deviceType",
        "path": "Device.type",
        "label": "Device",
        "control": "snomed",
        "min": 0,
        "max": "1",
        "mustSupport": true,
        "binding": {
          "ecl": "<< 49062001 |Device (physical object)|",
          "title": "Device type",
          "note": "Search a medical device"
        },
        "system": "http://snomed.info/sct",
        "doc": {
          "short": "Type of device.\r\nPreferably valued by using SNOMED CT.\r\nThe absence of information, or of devices relevant for purpose of this IPS, shall be explicitly stated by using the codes included in the absent-or-unknown-devices-uv-ips value set.",
          "definition": "The kind or type of device.",
          "control": "0..1",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": false,
          "isSummary": false,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are preferred to http://hl7.org/fhir/uv/ips/ValueSet/medical-devices-uv-ips.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-device-eu-eps-definitions.html#Device.type"
        },
        "bindingMeta": {
          "strength": "preferred",
          "valueSet": "http://hl7.org/fhir/uv/ips/ValueSet/medical-devices-uv-ips",
          "pageUrl": "https://hl7.org/fhir/uv/ips/ValueSet-medical-devices-uv-ips.html",
          "isSct": true
        }
      },
      {
        "key": "status",
        "path": "DeviceUseStatement.status",
        "label": "Status",
        "control": "dropdown",
        "min": 1,
        "max": "1",
        "mustSupport": false,
        "options": [
          {
            "code": "active",
            "system": "http://hl7.org/fhir/device-statement-status",
            "display": "Active"
          },
          {
            "code": "completed",
            "system": "http://hl7.org/fhir/device-statement-status",
            "display": "Completed"
          },
          {
            "code": "intended",
            "system": "http://hl7.org/fhir/device-statement-status",
            "display": "Intended"
          },
          {
            "code": "on-hold",
            "system": "http://hl7.org/fhir/device-statement-status",
            "display": "On hold"
          },
          {
            "code": "stopped",
            "system": "http://hl7.org/fhir/device-statement-status",
            "display": "Stopped"
          },
          {
            "code": "entered-in-error",
            "system": "http://hl7.org/fhir/device-statement-status",
            "display": "Entered in error"
          }
        ],
        "system": "http://hl7.org/fhir/device-statement-status",
        "doc": {
          "short": "Current status of the Device Usage",
          "definition": "A code representing the patient or other source's judgment about the state of the device used that this statement is about.  Generally this will be active or completed.",
          "comment": "DeviceUseStatment is a statement at a point in time.  The status is only representative at the point when it was asserted.  The value set for contains codes that assert the status of the use  by the patient (for example, stopped or on hold) as well as codes that assert the status of the resource itself (for example, entered in error).\r\rThis element is labeled as a modifier because the status contains the codes that mark the statement as not currently valid.",
          "control": "1..1",
          "types": [
            "code"
          ],
          "isModifier": true,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are required to http://hl7.org/fhir/ValueSet/device-statement-status.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-deviceUseStatement-eu-eps-definitions.html#DeviceUseStatement.status"
        },
        "bindingMeta": {
          "strength": "required",
          "valueSet": "http://hl7.org/fhir/ValueSet/device-statement-status",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-device-statement-status.html",
          "isSct": false
        }
      },
      {
        "key": "timing",
        "path": "DeviceUseStatement.timing[x]",
        "label": "In use since",
        "control": "date",
        "min": 0,
        "max": "1",
        "mustSupport": true,
        "doc": {
          "short": "How often  the device was used",
          "definition": "How often the device was used.",
          "control": "0..1",
          "types": [
            "Timing",
            "Period",
            "dateTime"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-deviceUseStatement-eu-eps-definitions.html#DeviceUseStatement.timing[x]"
        }
      },
      {
        "key": "bodySite",
        "path": "DeviceUseStatement.bodySite",
        "label": "Body site",
        "control": "snomed",
        "min": 0,
        "max": "1",
        "mustSupport": false,
        "binding": {
          "ecl": "<< 123037004 |Body structure (body structure)|",
          "title": "Body site",
          "note": "Search a body structure"
        },
        "system": "http://snomed.info/sct",
        "doc": {
          "short": "Target body site",
          "definition": "Indicates the anotomic location on the subject's body where the device was used ( i.e. the target).",
          "control": "0..1",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are preferred to http://hl7.org/fhir/ValueSet/body-site.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-deviceUseStatement-eu-eps-definitions.html#DeviceUseStatement.bodySite"
        },
        "bindingMeta": {
          "strength": "preferred",
          "valueSet": "http://hl7.org/fhir/ValueSet/body-site",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-body-site.html",
          "isSct": true
        }
      }
    ]
  },
  {
    "key": "travelHistory",
    "kind": "resource",
    "title": "Travel History",
    "loincCode": "10182-4",
    "resourceType": "Observation",
    "profile": "http://hl7.eu/fhir/eps/StructureDefinition/observation-travel-eu-eps",
    "profilePageUrl": "https://hl7.eu/fhir/eps/StructureDefinition-observation-travel-eu-eps.html",
    "icon": "flight",
    "description": "Countries visited, relevant for exposure and infectious risk.",
    "fields": [
      {
        "key": "country",
        "path": "Observation.value[x]",
        "label": "Country visited",
        "control": "dropdown",
        "min": 1,
        "max": "1",
        "mustSupport": false,
        "options": [
          {
            "code": "AT",
            "system": "urn:iso:std:iso:3166",
            "display": "Austria"
          },
          {
            "code": "BE",
            "system": "urn:iso:std:iso:3166",
            "display": "Belgium"
          },
          {
            "code": "BR",
            "system": "urn:iso:std:iso:3166",
            "display": "Brazil"
          },
          {
            "code": "CA",
            "system": "urn:iso:std:iso:3166",
            "display": "Canada"
          },
          {
            "code": "CH",
            "system": "urn:iso:std:iso:3166",
            "display": "Switzerland"
          },
          {
            "code": "CN",
            "system": "urn:iso:std:iso:3166",
            "display": "China"
          },
          {
            "code": "DE",
            "system": "urn:iso:std:iso:3166",
            "display": "Germany"
          },
          {
            "code": "DK",
            "system": "urn:iso:std:iso:3166",
            "display": "Denmark"
          },
          {
            "code": "EG",
            "system": "urn:iso:std:iso:3166",
            "display": "Egypt"
          },
          {
            "code": "ES",
            "system": "urn:iso:std:iso:3166",
            "display": "Spain"
          },
          {
            "code": "FR",
            "system": "urn:iso:std:iso:3166",
            "display": "France"
          },
          {
            "code": "GB",
            "system": "urn:iso:std:iso:3166",
            "display": "United Kingdom"
          },
          {
            "code": "GR",
            "system": "urn:iso:std:iso:3166",
            "display": "Greece"
          },
          {
            "code": "IE",
            "system": "urn:iso:std:iso:3166",
            "display": "Ireland"
          },
          {
            "code": "IN",
            "system": "urn:iso:std:iso:3166",
            "display": "India"
          },
          {
            "code": "IT",
            "system": "urn:iso:std:iso:3166",
            "display": "Italy"
          },
          {
            "code": "JP",
            "system": "urn:iso:std:iso:3166",
            "display": "Japan"
          },
          {
            "code": "KE",
            "system": "urn:iso:std:iso:3166",
            "display": "Kenya"
          },
          {
            "code": "MX",
            "system": "urn:iso:std:iso:3166",
            "display": "Mexico"
          },
          {
            "code": "NL",
            "system": "urn:iso:std:iso:3166",
            "display": "Netherlands"
          },
          {
            "code": "NO",
            "system": "urn:iso:std:iso:3166",
            "display": "Norway"
          },
          {
            "code": "PT",
            "system": "urn:iso:std:iso:3166",
            "display": "Portugal"
          },
          {
            "code": "SE",
            "system": "urn:iso:std:iso:3166",
            "display": "Sweden"
          },
          {
            "code": "TH",
            "system": "urn:iso:std:iso:3166",
            "display": "Thailand"
          },
          {
            "code": "TR",
            "system": "urn:iso:std:iso:3166",
            "display": "Türkiye"
          },
          {
            "code": "US",
            "system": "urn:iso:std:iso:3166",
            "display": "United States"
          },
          {
            "code": "ZA",
            "system": "urn:iso:std:iso:3166",
            "display": "South Africa"
          }
        ],
        "system": "urn:iso:std:iso:3166",
        "doc": {
          "short": "Country visited",
          "definition": "The country visited.",
          "comment": "An observation may have; 1)  a single value here, 2)  both a value and a set of related or component values,  or 3)  only a set of related or component values. If a value is present, the datatype for this element should be determined by Observation.code.  A CodeableConcept with just a text would be used instead of a string if the field was usually coded, or if the type associated with the Observation.code defines a coded value.  For additional guidance, see the [Notes section](http://hl7.org/fhir/R4/observation.html#notes) below.",
          "control": "1..1",
          "types": [
            "CodeableConcept"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are required to http://hl7.org/fhir/ValueSet/iso3166-1-2.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-observation-travel-eu-eps-definitions.html#Observation.value[x]"
        },
        "bindingMeta": {
          "strength": "required",
          "valueSet": "http://hl7.org/fhir/ValueSet/iso3166-1-2",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-iso3166-1-2.html",
          "isSct": false
        }
      },
      {
        "key": "effective",
        "path": "Observation.effective[x]",
        "label": "Date / period",
        "control": "date",
        "min": 0,
        "max": "1",
        "mustSupport": false,
        "doc": {
          "short": "Clinically relevant time/time-period for observation",
          "definition": "The time or time-period the observed value is asserted as being true. For biological subjects - e.g. human patients - this is usually called the \"physiologically relevant time\". This is usually either the time of the procedure or of specimen collection, but very often the source of the date/time is not known, only the date/time itself.",
          "comment": "At least a date should be present unless this observation is a historical report.  For recording imprecise or \"fuzzy\" times (For example, a blood glucose measurement taken \"after breakfast\") use the [Timing](http://hl7.org/fhir/R4/datatypes.html#timing) datatype which allow the measurement to be tied to regular life events.",
          "control": "0..1",
          "types": [
            "dateTime",
            "Period",
            "Timing",
            "instant"
          ],
          "isModifier": false,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-observation-travel-eu-eps-definitions.html#Observation.effective[x]"
        }
      },
      {
        "key": "status",
        "path": "Observation.status",
        "label": "Status",
        "control": "dropdown",
        "min": 1,
        "max": "1",
        "mustSupport": false,
        "options": [
          {
            "code": "final",
            "system": "http://hl7.org/fhir/observation-status",
            "display": "Final"
          },
          {
            "code": "preliminary",
            "system": "http://hl7.org/fhir/observation-status",
            "display": "Preliminary"
          },
          {
            "code": "amended",
            "system": "http://hl7.org/fhir/observation-status",
            "display": "Amended"
          },
          {
            "code": "entered-in-error",
            "system": "http://hl7.org/fhir/observation-status",
            "display": "Entered in error"
          }
        ],
        "system": "http://hl7.org/fhir/observation-status",
        "doc": {
          "short": "The status of the observation.",
          "definition": "The status of the result value.",
          "comment": "This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid.",
          "control": "1..1",
          "types": [
            "code"
          ],
          "isModifier": true,
          "isSummary": true,
          "invariants": [
            "ele-1"
          ],
          "bindingText": "The codes are required to http://hl7.org/fhir/ValueSet/observation-status.",
          "definitionUrl": "https://hl7.eu/fhir/eps/StructureDefinition-observation-travel-eu-eps-definitions.html#Observation.status"
        },
        "bindingMeta": {
          "strength": "required",
          "valueSet": "http://hl7.org/fhir/ValueSet/observation-status",
          "pageUrl": "https://hl7.org/fhir/R4/valueset-observation-status.html",
          "isSct": false
        }
      }
    ]
  },
  {
    "key": "patientStory",
    "kind": "narrative",
    "title": "Patient Story",
    "loincCode": "81338-6",
    "resourceType": "Composition",
    "profile": "http://hl7.eu/fhir/eps/StructureDefinition/composition-eu-eps",
    "profilePageUrl": "https://hl7.eu/fhir/eps/StructureDefinition-composition-eu-eps.html",
    "icon": "menu_book",
    "description": "The patient’s own narrative — goals, preferences and concerns.",
    "fields": []
  },
  {
    "key": "patientHistory",
    "kind": "narrative",
    "title": "History of Past Illness",
    "loincCode": "11329-0",
    "resourceType": "Composition",
    "profile": "http://hl7.eu/fhir/eps/StructureDefinition/composition-eu-eps",
    "profilePageUrl": "https://hl7.eu/fhir/eps/StructureDefinition-composition-eu-eps.html",
    "icon": "history_edu",
    "description": "Narrative summary of the patient’s past medical history.",
    "fields": []
  }
];
